### PR TITLE
Un-break snapshot creation (can't use regex on a dict)

### PR DESCRIPTION
**Pull request by broxeph**

### CODE REVIEW

**Comment by chrisspen** [comment]
No, the original's correct. The options configuration in our code is wrong, which I've fixed.

**Comment by broxeph** [comment]
Okay, but this is still going to throw an unhelpful `TypeError` in the case of missing dict keys, rather than something more useful like a `KeyError`. Mentioning this because I can't imagine `'options' or ''` was intended behavior...

**Comment by chrisspen** [comment]
Yes, that is intended, because 'options' is a string. It's 'OPTIONS' that's a dictionary.

**Comment by broxeph** [comment]
Right, but my point was that the expression `'options' or ''` will always evaluate to `'options'`, which led me to believe there was a typo and/or unintended behavior. When `OPTIONS` is missing or is an empty dict, you're calling `{}.get('options' or '')`, which will evaluate to `None`, and will throw a `TypeError` when used in `re.findall()`.

I assumed the intention was `{}.get('options', '')`, which evaluates to the empty string, can therefore be used in regex, and when the resulting list's nonexistent first index is accessed, will throw an `IndexError`, which is properly handled on the next line.

**Comment by chrisspen** [comment]
Yep, you're right.

**Pull request merged**
